//Create a Course
###
POST http://localhost:8081/course/createCourse
Content-Type: application/json 

{
    "title" : "Dog 7",
    "description": "I am a testing body in .rest"
   
}

###
POST http://localhost:8081/course/createCourse
Content-Type: application/json 

{
    "title" : "cat 7",
    "description": "I am a testing body in .rest",
    "section": "6414d50efb96d06b8f2bd178",
    "content":"Body of the course",
    "quizzes:":
   
}

//Get all courses course
###
GET http://localhost:8081/course/getAllCourses
Content-Type: application/json

//Get course by ID
###
GET http://localhost:8081/course/getCourseById/63eb3ee13998babbd1698f55
Content-Type: application/json 


//Delete course by ID
###
DELETE  http://localhost:8081/course/deleteCourseById/64355e57cea8384bd2602104
Content-Type: application/json 


//Update a course by ID
###
PUT  http://localhost:8081/course/updateCourseById/63fc275914fc43434724d82d
Content-Type: application/json 

{
    "title" : "Dog 10",
    "description": "Better than Dog 4"
}



