//Create a Quiz
POST http://localhost:8081/quiz/createQuiz
Content-Type: application/json 

{
  "title": "Sample Quiz",
  "questions": [
    "What is the capital of France?",
    "What is the currency of Japan?"
  ],
  "options": [
    ["Paris", "Berlin", "London"],
    ["Yen", "Won", "Dollar"]
  ],
  "correctAnswers": [0, 2],
  "explanation": "Paris is the capital of France, and Yen is the currency of Japan",
  "course": "63fbe25f9d90c7a454c03c5b"
}



//Create another Quiz
###
POST http://localhost:8081/quiz/createQuiz
Content-Type: application/json

{
"title" : "Quiz 2",
    "questions": [],
    "options":[],
    "correctAnswers": [],
    "explanation": "No"
}

//Get all Quizzes
###
GET http://localhost:8081/quiz/getAllQuizzes
Content-Type: application/json
//Get all courses 
###
GET http://localhost:8081/course/getAllCourses
Content-Type: application/json


//Get quiz by ID
###
GET http://localhost:8081/quiz/getQuizById/63fbbe369750dec3338e51c4
Content-Type: application/json



//Delete quiz by ID
###
DELETE http://localhost:8081/quiz/deleteQuizById/63fbbe2f9750dec3338e51c2
Content-Type: application/json

//Update a quiz by ID
###
PUT http://localhost:8081/quiz/updateQuizById/63fb9ee749186b877e770eec
Content-Type: application/json

{
    "title" : "Quiz 1",
    "explanation": "Yes"
}

//Add an existing quiz to a course
###
POST http://localhost:8081/quiz/courses/63fbbe369750dec3338e51c4/quizzes/63fbbe2f9750dec3338e51c2
Content-Type: application/json

//Delete a quiz from a course without deleting the course
###
DELETE http://localhost:8081/quiz/courses/63fba3ff5a5251beee2f9313/quizzes/63fba2e65a5251beee2f9303

Content-Type: application/json